### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by deckar01** [Haskell-Things/ImplicitCAD#213]
The `rands(min, max, count)` RNG function does not currently seem to be supported. It would be nice if there was a shortcut for generating a single value also `rand(min, max)`.

**Comment by wbrickner** [comment]
I would also love this, I want to do procedural modeling of organic structures.

I am clueless when it comes to Haskell, but if the maintainer/s have time I would very deeply appreciate it! API doesn't need to match that of OpenSCAD for my purposes, anything would work.

Thanks everyone for all your hard work, very valuable.

**Comment by lepsa** [comment]
@julialongtin Should this be closed now that `rands` is merged?

**Comment by julialongtin** [comment]
@lepsa yep! this will be in our next release, folks!
