### ISSUE TITLE
More functions as parameters

### ISSUE THREAD

**Issue by brad** [Haskell-Things/ImplicitCAD#38]
I love the ability of ImplicitCAD to use a function for the twist parameter of linear_extrude and I think it would be amazing is this were available in more places.
Some good examples would be the radius of circles and spheres. Maybe even the radius of a cylinder, which could vary with the height as well as the arc angle.

I was hoping to produce a wavy circle with this:

``` shell
Prelude Graphics.Implicit> writeSVG 1 "test.svg" (let r x = sin(x) in circle(r))

<interactive>:1:51:
    Couldn't match expected type `Float' with actual type `a0 -> a0'
    Expected type: Graphics.Implicit.Definitions.â


    In the first argument of `circle', namely `(r)'
    In the expression: circle (r)
```

**Comment by julialongtin** [comment]
Closing this, as "more" is not a goal that has a defined ending. :)
