### ISSUE TITLE
Implement Multimatrix Function

### ISSUE THREAD

**Issue by solidboredom** [Haskell-Things/ImplicitCAD#397]
Hello, i would like to try implicitcad to render the CSG produced by openscad, with my complex models, using full set of openscads functionality including modules() openscad gets unbearably slow, where its CSG production is still kind of bearable.
my code produces a lor of multmatrixes in the csg file. is there a way to make implicitCad understand Multmatrix() like openscad does to be able to directly interpretcomplex CSG's? or even compex openscad scripts?

**Comment by julialongtin** [comment]
Possible? yes. likely? maybe. looks simple enough.
