### ISSUE TITLE
ExtOpenScad Let block of function definition gets wrong arguments

### ISSUE THREAD

**Issue by acoth** [Haskell-Things/ImplicitCAD#431]
Accessing function arguments normally works as expected,  but within a let block, it gets the previous argument instead.
Simple example:
`    function foo(a,b,c) = let(output=b) [output,b];
    echo(foo(1,2,3));`

returns `[1.0,2.0]` instead of the expected `[2.0,2.0]`

**Comment by lepsa** [comment]
@julialongtin I think that this can be closed now.
