### ISSUE TITLE
Switch `torus` and `ellipsoid` to `SymbolicObj3`

### ISSUE THREAD

**Issue by sorki** [Haskell-Things/ImplicitCAD#450]
These are currently implemented "inline" using `implicit` which makes them unique and opaque to our AST.

This reminded me of the Haskell expression problem https://eli.thegreenplace.net/2018/more-thoughts-on-the-expression-problem-in-haskell/ and one of the solutions [Data Types a la Carte](http://www.cs.ru.nl/~W.Swierstra/Publications/DataTypesALaCarte.pdf)

Search for DTalC led me to familiar site https://reasonablypolymorphic.com/blog/better-data-types-a-la-carte/ which offers improved version.

Switching to this representation would allow us and our users to extend our current monolithic AST types with custom ones.

**Comment by julialongtin** [comment]
done. :)
