### ISSUE TITLE
Implement better pretty printer for `escad`

### ISSUE THREAD

**Issue by sorki** [Haskell-Things/ImplicitCAD#455]
Using for example [`prettyprinter` library](https://hackage.haskell.org/package/prettyprinter)

The current output could be improved with indentation and could serve as a basis for formatter (e.g. `extopenscad format` subcommand).

Related to #456

**Comment by sorki** [comment]
Would also enable colors in terminal output!

**Comment by julialongtin** [comment]
fixed with PR#455.
